### PR TITLE
Show indicator for validation status

### LINKED ISSUE #75: No way to show validation status in the example app

### PR DESCRIPTION
**Pull request by iamsahilsonawane**
## Connection with issue(s)
Closes #75

## Solution description
Shows validation indicator on **Validate** button press.

## Screenshots or Videos
https://user-images.githubusercontent.com/47249618/182874913-0110e807-aa1d-495e-90c6-fac86adf078a.mp4

## To Do

- [x] Read [contributing guide](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CONTRIBUTING.md)
- [x] Check the original issue to confirm it is fully satisfied
- [x] Add solution description to help guide reviewers
- [ ] Add unit test to verify new or fixed behaviour
- [x] If apply, add documentation to code properties and package readme

### CODE REVIEW

**Review by deandreamatias — APPROVED** [review]

**Comment by deandreamatias** [comment]
For me is ok but we need simplify the example in the future to make more easy the understand

**Comment by iamsahilsonawane** [comment]
About snackbar? Yes now that I am thinking about it, I agree with you. 

No problem, I'll remove the utility and call a normal snackbar instead

**Comment by deandreamatias** [comment]
Its about all, not only the snackbar
Complex state managemet for example app, is overthink
But of course that isn't your fault or only of this PR, is from old code

**Comment by iamsahilsonawane** [comment]
I see, let's as add it to the roadmap 👍

**Pull request merged**
