### PR TITLE
Add some docs and pipeline

### LINKED ISSUE #66: Add minimal validation workflow
## Environment

**Package version:** N/A

## Description

**What you'd like to happen:**
Has a minimal workflow with Github actions to verify code
- Analyze static code
- Build example
- Check broken links

**Alternatives you've considered:**
Copy from flutter_form_builder repo https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/tree/master/.github/workflows

### PR DESCRIPTION
**Pull request by deandreamatias**
Close #66

### CODE REVIEW

**Comment by deandreamatias** [comment]
I don't know how solve android build error. In my local machine with Linux and Android simulator, works fine.
Take a look if you want @iamsahilsonawane

**Comment by iamsahilsonawane** [comment]
I see, I think this is due to the older version of Gradle. I'll fix this soon today

**Comment by iamsahilsonawane** [comment]
Post Gradle update, it's still failing. Was a follow-up from [this](https://github.com/subosito/flutter-action/issues/116). Working on for some more solutions

**Comment by iamsahilsonawane** [comment]
@deandreamatias I am not sure about the "Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8." error it's giving, this should automatically be java 11 already from the actions, right? Do we have to include the flutter version may be in the actions config?

**Comment by iamsahilsonawane** [comment]
@deandreamatias Issue has been fixed. We're ready to merge now ⚡

**Comment by deandreamatias** [comment]
I don't know if this update break plugin in some old devices. We should be test this maybe

**Comment by iamsahilsonawane** [comment]
It is a possibility, also we should add some automated tests and update the actions.

**Pull request merged**
